split_train_val:
  val_size: 0.2
  seed: 42
  stratify: True
  
data_preprocess:
  source_directory: '/datasets/FHI2020_Stratified_Sampling/'
  target_directory: '/datasets/FHI2020_Stratified_Sampling/processed'

train_model:
  model_name: RandomForestClassifier
  model_params:
    n_estimators: 100
    max_depth: 
    random_state: 42
    n_jobs: -1